export const Info_Past1 = {
    baner_title_part1: 'Sevan Startup Summit 2018',
    baner_title_part2: 'Sevan Startup Summit 2018',
    event_date: 'Armenia. Lake Sevan. July 22-29, 2018',
    aftermovie_link: 'https://www.youtube.com/embed/FkDxAiIaLzY',
    diaries_title: 'Sevan Startup Summit 2018 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/MLIOtkr8jr8',
    diaries_button_link: [
        { id: 1, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/MLIOtkr8jr8?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/MLIOtkr8jr8/default.jpg' },
        { id: 2, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/v1_w2h-kvbo?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/v1_w2h-kvbo/default.jpg' },
        { id: 3, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/PQpw-Hbfu3U?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/PQpw-Hbfu3U/default.jpg' },
        { id: 4, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/aP4i9_S-XUg?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/aP4i9_S-XUg/default.jpg' },
        { id: 5, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/-bJfCJGeqHY?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/-bJfCJGeqHY/default.jpg' },
        { id: 6, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/Ac1rO7xdaR8?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/Ac1rO7xdaR8/default.jpg' },
        { id: 7, title: 'Sevan Startup Summit 2018', link: 'https://www.youtube.com/embed/5nZAtp7UYzE?list=PLCcLpJIHQ5vf5sjAEaM4b1es76U_sIj0j&autoplay=1', img: 'https://i1.ytimg.com/vi/5nZAtp7UYzE/default.jpg' },
    ],
    infographic_title: 'Sevan Startup Summit 2018 in numbers exceeded all the previous ones',
    infographic_1: '150',
    infographic_2: 'US $100K',
    infographic_3: 'US $1mln',
    infographic_4: '20+',
    infographic_5: '5,000',
    infographic_6: '80',
    spiker_push: '/sevan18',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakers18&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartups18&id',
    API_IMG_URL: 'sevan_2018/img',
    baner_class: 'sevan18_baner',
    metaTitle:"Sevan Startup Summit 2018 | Seaside Startup Summit",
    metaDesc:"Sevan Startup Summit 2018 was held at Sevan seashore from July 24 to July 29.",
    metaImg:"sevan18.jpg"
}
export const Info_Past2 = {
    baner_title_part1: 'Sevan Startup Summit 2017',
    baner_title_part2: 'Sevan Startup Summit 2017',
    event_date: 'Armenia. Lake Sevan. July 24-29, 2017',
    aftermovie_link: 'https://www.youtube.com/embed/30JZ1-fd-SQ',
    diaries_title: 'Sevan Startup Summit 2017 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/IXGf_aF-5Bc?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ',
    diaries_button_link: [
        { id: 1, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/IXGf_aF-5Bc?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/IXGf_aF-5Bc/default.jpg' },
        { id: 2, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/L2wzTvtAbfI?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/L2wzTvtAbfI/default.jpg' },
        { id: 3, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/G2j4ZeOn1C8?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/G2j4ZeOn1C8/default.jpg' },
        { id: 4, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/7e0MQYllOTU?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/7e0MQYllOTU/default.jpg' },
        { id: 5, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/CYLa8PDnWWI?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/CYLa8PDnWWI/default.jpg' },
        { id: 6, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/L3R9wybXZ4o?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/L3R9wybXZ4o/default.jpg' },
        { id: 7, title: 'Sevan Startup Summit 2017', link: 'https://www.youtube.com/embed/EiOoRQtc7Ac?list=PLCcLpJIHQ5vdLzpsnGNXZReHcpTiUEkdZ&autoplay=1', img: 'https://i1.ytimg.com/vi/EiOoRQtc7Ac/default.jpg' },
    ],
    infographic_title: 'Sevan Startup Summit 2017 in numbers exceeded all the previous ones',
    infographic_1: '109',
    infographic_2: 'US $50K',
    infographic_3: 'US $50K',
    infographic_4: '21',
    infographic_5: '4,000',
    infographic_6: '78',
    spiker_push: '/sevan17',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakers17&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartups17&id',
    API_IMG_URL: 'sevan_2017/img',
    baner_class: 'sevan17_baner',
    metaTitle:"Sevan Startup Summit 2017 | Seaside Startup Summit",
    metaDesc:"Sevan Startup Summit 2017 was held at Sevan seashore from July 24 to July 29.",
    metaImg:"sevan17.jpg"
}
export const Info_Past3 = {
    baner_title_part1: 'Sevan Startup Summit 2016',
    baner_title_part2: 'Sevan Startup Summit 2016',
    event_date: 'Armenia. Lake Sevan. Aug 18-27, 2016',
    aftermovie_link: 'https://www.youtube.com/embed/j2D2o7C0xoY?list=PLCcLpJIHQ5vf0Sru8mg0P7T8xWt5SiMb1',
    diaries_title: 'Sevan Startup Summit 2016 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/jWFguXLDCqo?list=PLCcLpJIHQ5vf0Sru8mg0P7T8xWt5SiMb1',
    diaries_button_link: [
        { id: 1, title: 'Sevan Startup Summit 2016', link: 'https://www.youtube.com/embed/jWFguXLDCqo?list=PLCcLpJIHQ5vf0Sru8mg0P7T8xWt5SiMb1&autoplay=1', img: 'https://i1.ytimg.com/vi/jWFguXLDCqo/default.jpg' },
        { id: 2, title: 'Sevan Startup Summit 2016', link: 'https://www.youtube.com/embed/VeuO7YfHrRA?list=PLCcLpJIHQ5vf0Sru8mg0P7T8xWt5SiMb1&autoplay=1', img: 'https://i1.ytimg.com/vi/VeuO7YfHrRA/default.jpg' },
    ],
    infographic_title: 'Sevan Startup Summit 2016 in numbers exceeded all the previous ones',
    infographic_1: '32',
    infographic_2: 'US $7.5K',
    infographic_3: 'US $35K',
    infographic_4: '5',
    infographic_5: '1,000',
    infographic_6: '25',
    spiker_push: '/sevan16',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakers16&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartups16&id',
    API_IMG_URL: 'sevan_2016/img',
    baner_class: 'sevan16_baner',
    metaTitle:"Sevan Startup Summit 2016 | Seaside Startup Summit",
    metaDesc:"Sevan Startup Summit 2016 was held at Sevan seashore from August 18 to August 27.",
    metaImg:"sevan16.png"
}
export const Info_Past4 = {
    baner_title_part1: 'Seaside Startup Summit UAE RAK',
    baner_title_part2: 'Seaside Startup Summit UAE RAK',
    event_date: 'Al Marjan Island, UAE. Feb 8-12, 2018',
    aftermovie_link: 'https://www.youtube.com/embed/7RG0wH9t3UA',
    diaries_title: 'Seaside Startup Summit UAE 2018 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/oszYU0o9ZqU?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-',
    diaries_button_link: [
        { id: 1, title: 'Seaside Startup Summit 2018 UAE', link: 'https://www.youtube.com/embed/oszYU0o9ZqU?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-&autoplay=1', img: 'https://i1.ytimg.com/vi/oszYU0o9ZqU/default.jpg' },
        { id: 2, title: 'Seaside Startup Summit 2018 UAE', link: 'https://www.youtube.com/embed/qruToaQEA-k?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-&autoplay=1', img: 'https://i1.ytimg.com/vi/qruToaQEA-k/default.jpg' },
        { id: 3, title: 'Seaside Startup Summit 2018 UAE', link: 'https://www.youtube.com/embed/7YNvzaCZ94c?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-&autoplay=1', img: 'https://i1.ytimg.com/vi/7YNvzaCZ94c/default.jpg' },
        { id: 4, title: 'Seaside Startup Summit 2018 UAE', link: 'https://www.youtube.com/embed/Kwk0iVf5sKY?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-&autoplay=1', img: 'https://i1.ytimg.com/vi/Kwk0iVf5sKY/default.jpg' },
        { id: 5, title: 'Seaside Startup Summit 2018 UAE', link: 'https://www.youtube.com/embed/Cc7AqClKXFg?list=PLCcLpJIHQ5vePrfk40MAlBPPBYIf7Q7A-&autoplay=1', img: 'https://i1.ytimg.com/vi/Cc7AqClKXFg/default.jpg' },
    ],
    infographic_title: 'Seaside Startup Summit UAE in numbers exceeded all the previous ones',
    infographic_1: '60',
    infographic_2: 'US $44K',
    infographic_3: 'US $875K',
    infographic_4: '7',
    infographic_5: '1,500',
    infographic_6: '51',
    spiker_push: '/uae18',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakersRak18&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartupsRak18&id',
    API_IMG_URL: 'rak_2018/img',
    baner_class: 'rak18_baner',
    metaTitle:"Seaside Startup Summit UAE RAK | Seaside Startup Summit",
    metaDesc:"Seaside Startup Summit UAE RAK  was held at Al Marjan Island from February 8 to February 12.",
    metaImg:"uae18.jpg"
}
export const Info_Past5 = {
    baner_title_part1: 'Seaside Startup Summit India Goa',
    baner_title_part2: 'Seaside Startup Summit India Goa',
    event_date: 'Cabo De Rama, India. Mar 6-11, 2018',
    aftermovie_link: 'https://www.youtube.com/embed/3l5_QQv2d2g',
    diaries_title: 'Seaside Startup Summit India 2018 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/wO06yhwfT6g?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv',
    diaries_button_link: [
        { id: 1, title: 'Seaside Startup Summit 2018 India', link: 'https://www.youtube.com/embed/wO06yhwfT6g?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv&autoplay=1', img: 'https://i1.ytimg.com/vi/wO06yhwfT6g/default.jpg' },
        { id: 2, title: 'Seaside Startup Summit 2018 India', link: 'https://www.youtube.com/embed/XuFuMxiaubY?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv&autoplay=1', img: 'https://i1.ytimg.com/vi/XuFuMxiaubY/default.jpg' },
        { id: 3, title: 'Seaside Startup Summit 2018 India', link: 'https://www.youtube.com/embed/hj3t2Zqcq3o?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv&autoplay=1', img: 'https://i1.ytimg.com/vi/hj3t2Zqcq3o/default.jpg' },
        { id: 4, title: 'Seaside Startup Summit 2018 India', link: 'https://www.youtube.com/embed/pMHvw8ZHCxE?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv&autoplay=1', img: 'https://i1.ytimg.com/vi/pMHvw8ZHCxE/default.jpg' },
        { id: 5, title: 'Seaside Startup Summit 2018 India', link: 'https://www.youtube.com/embed/f2S-s6Y-5cE?list=PLCcLpJIHQ5veaPYA6nOPH-RY9SnSNa-Dv&autoplay=1', img: 'https://i1.ytimg.com/vi/f2S-s6Y-5cE/default.jpg' },
    ],
    infographic_title: 'Seaside Startup Summit India in numbers exceeded all the previous ones',
    infographic_1: '89',
    infographic_2: 'US $22K',
    infographic_3: 'US $300K',
    infographic_4: '8',
    infographic_5: '1,600',
    infographic_6: '80',
    spiker_push: '/india18',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakersGoa18&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartupsGoa18&id',
    API_IMG_URL: 'goa_2018/img',
    baner_class: 'goa18_baner',
    metaTitle:"Seaside Startup Summit India GOA | Seaside Startup Summit",
    metaDesc:"Seaside Startup Summit India GOA  was held at Cabo De Rama from March 6 to March 11.",
    metaImg:"india18.jpg"
}
export const Info_Past6 = {
    baner_title_part1: 'Sevan Startup Summit 2019',
    baner_title_part2: 'Sevan Startup Summit 2019',
    event_date: 'Armenia. Lake Sevan. July 28 - August 3, 2019',
    aftermovie_link: 'https://www.youtube.com/embed/2EQFRmIHSBs',
    diaries_title: 'Sevan Startup Summit 2019 Diaries',
    diaries_main_link: 'https://www.youtube.com/embed/plEjdCeqhRA',
    diaries_button_link: [
        { id: 1, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/plEjdCeqhRA?autoplay=1', img: 'https://i1.ytimg.com/vi/MLIOtkr8jr8/default.jpg' },
        { id: 2, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/uTjN4eQQYjM?autoplay=1', img: 'https://i1.ytimg.com/vi/v1_w2h-kvbo/default.jpg' },
        { id: 3, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/WS8FUKmGK78?autoplay=1', img: 'https://i1.ytimg.com/vi/PQpw-Hbfu3U/default.jpg' },
        { id: 4, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/Ky-HXtHUuIs?autoplay=1', img: 'https://i1.ytimg.com/vi/aP4i9_S-XUg/default.jpg' },
        { id: 5, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/uHNipxY5Ljc?autoplay=1', img: 'https://i1.ytimg.com/vi/-bJfCJGeqHY/default.jpg' },
        { id: 6, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/9ETJ9XYdGRY?autoplay=1', img: 'https://i1.ytimg.com/vi/Ac1rO7xdaR8/default.jpg' },
        { id: 7, title: 'Sevan Startup Summit 2019', link: 'https://www.youtube.com/embed/Rj_rot6Tsvg?autoplay=1', img: 'https://i1.ytimg.com/vi/5nZAtp7UYzE/default.jpg' },
    ],
    infographic_title: 'Sevan Startup Summit 2019 in numbers exceeded all the previous ones',
    infographic_1: '150',
    infographic_2: 'US $100K',
    infographic_3: 'US $1,2mln',
    infographic_4: '30+',
    infographic_5: '10,000',
    infographic_6: '100+',
    spiker_push: '/sevan19',
    API_SPEAKER_URL: 'https://www.apis.seasidestartupsummit.com/past/speakers/?method=getSpeakers19&id',
    API_STARTUP_URL: 'https://www.apis.seasidestartupsummit.com/past/startups/?method=getStartups19&id',
    API_IMG_URL: 'sevan_2019/img',
    baner_class: 'sevan19_baner',
    metaTitle:"Sevan Startup Summit 2019 | Seaside Startup Summit",
    metaDesc:"Sevan Startup Summit 2019 was held at Sevan seashore from July 28 to August 3.",
    metaImg:"sevan19.jpg"
}